name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
