

name: Test Go Install

on:
  workflow_dispatch:

jobs:
  test-install:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure git to use public git protocol
        run: git config --global url."git://github.com/".insteadOf "https://github.com/"

      - uses: actions-go/go-install@main
        with:
          module: "github.com/fatuma-tahalil/markscribe@main"

      - run: markscribe --version
