name: Update README with Markscribe

on:
  schedule:
    - cron: "0 * * * *" # hourly updates
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update README using Markscribe
        uses: markscribe/markscribe-action@v1
        with:
          template: |
            # Hey 👾  
            I forgot how to code :b  
            
            <img src="https://github-readme-stats.hackclub.dev/api/wakatime?username=3788&api_domain=hackatime.hackclub.com&theme=dracula&custom_title=Hackatime+Stats&layout=compact&cache_seconds=0&langs_count=8">

            {{ wakatimeDoubleCategoryBar "💾 Languages:" wakatimeData.Languages "💼 Projects:" wakatimeData.Projects 5 }}
          output: README.md
        env:
          MARKSCRIBE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKSCRIBE_HACKATIME_API_KEY: ${{ secrets.HACKATIME_API_KEY }}
