name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update WakaTime stats
        uses: fatuma-tahalil/famat@master
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          commit_message: '📈 Update WakaTime stats'
