name: Waka Readme

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: windows-latest
    steps:
      - uses: fatuma-tahalil/famat@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
